# Generated by Django 3.2.4 on 2021-06-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='criacao',
            field=models.DateField(verbose_name='Data de criação'),
        ),
    ]
