# Generated by Django 3.2.4 on 2021-06-05 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_atividade_criacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='id',
        ),
        migrations.AddField(
            model_name='atividade',
            name='id_atividade',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='criacao',
            field=models.DateField(auto_now_add=True, verbose_name='Data de criação'),
        ),
    ]
