# Generated by Django 3.2.4 on 2021-06-05 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0003_auto_20210605_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='criacao',
            field=models.DateField(verbose_name='Data de criação'),
        ),
    ]
