# Generated by Django 3.2.4 on 2021-06-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20210605_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='id_atividade',
        ),
        migrations.AddField(
            model_name='atividade',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
